// This file is generated by Firebase Studio.
'use server';
/**
 * @fileOverview Generates a dynamic greeting message.
 *
 * - generateGreeting - A function that generates a personalized greeting message.
 * - GreetingInput - The input type for the generateGreeting function.
 * - GreetingOutput - The return type for the generateGreeting function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GreetingInputSchema = z.object({
  name: z.string().describe('The name of the visitor.'),
});

export type GreetingInput = z.infer<typeof GreetingInputSchema>;

const GreetingOutputSchema = z.object({
  greetings: z.array(z.string()).describe('A list of welcome messages.'),
});

export type GreetingOutput = z.infer<typeof GreetingOutputSchema>;

export async function generateGreeting(input: GreetingInput): Promise<GreetingOutput> {
  return generateGreetingFlow(input);
}

const prompt = ai.definePrompt({
  name: 'dynamicGreetingPrompt',
  input: {schema: GreetingInputSchema},
  output: {schema: GreetingOutputSchema},
  prompt: `Generate a single, simple welcome message for a visitor named {{name}}. It should just say "Welcome, {{name}}!"`,
  model: 'googleai/gemini-2.0-flash',
});

const generateGreetingFlow = ai.defineFlow(
  {
    name: 'generateGreetingFlow',
    inputSchema: GreetingInputSchema,
    outputSchema: GreetingOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
